"""
Django settings for authentium project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import logging
import os
import sys
from authentium.apps.base.utility.io import confirm_dir_exists
from django.urls.base import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

FILES_DIR = os.path.join(BASE_DIR, 'files')
confirm_dir_exists(FILES_DIR)

TEMPLATES_DIR = os.path.join(FILES_DIR, 'templates')
confirm_dir_exists(TEMPLATES_DIR)

STATIC_DIR = os.path.join(FILES_DIR, 'static')
confirm_dir_exists(STATIC_DIR)

STATIC_ROOT = os.path.join(FILES_DIR, 'assets')
confirm_dir_exists(STATIC_ROOT)

MEDIA_ROOT = os.path.join(FILES_DIR, 'media')
confirm_dir_exists(MEDIA_ROOT)

FIXTURES_ROOT = os.path.join(FILES_DIR, 'fixtures')
confirm_dir_exists(FIXTURES_ROOT)

FIXTURE_DIRS = [FIXTURES_ROOT, ]

STATICFILES_DIRS = [STATIC_DIR, ]

LOG_FILE_DIR = os.path.join(FILES_DIR, 'logs')
confirm_dir_exists(LOG_FILE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+-yk9agft6y@7+-%9_fuo^wu%1#h!hrd98^$zrmy*^i2z)a8z1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
BASE_URL = "http://localhost:8000/"
#BASE_URL = "http://52.66.73.23/"
AUTH_USER_MODEL = 'account.ModelAccountUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Authentium Apps
    'authentium.apps.account',
    'authentium.apps.base',
    'authentium.apps.site',
    'authentium.apps.market_place',


     #3rd party
     'rest_framework',
     'oauth2_provider',
     'corsheaders',
     'mailqueue',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'authentium.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'authentium.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'authentium',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'authentium',
#         'USER': 'authuser',
#         'PASSWORD': 'Saini@369',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}


MAILQUEUE_QUEUE_UP = True
# MAILQUEUE_CELERY = True

# EMAIL_HOST = 'Smtp.mailgun.org'
# EMAIL_HOST_USER = 'noreply@saavi.com.au'
# EMAIL_HOST_PASSWORD = '6E4$4q8k364s47i'
# #EMAIL_USE_SSL=True
# DEFAULT_FROM_EMAIL = 'mobileordering@saavi.com.au'
# EMAIL_USE_TLS = True

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'dokmeetesting@gmail.com'
EMAIL_HOST_PASSWORD = 'dokmee@369'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'dokmeetesting@gmail.com'
DEFAULT_LOGIN_REDIRECT_URL = reverse_lazy('account:dashboard')

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
