# Generated by Django 3.1.1 on 2020-09-27 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('email', models.EmailField(help_text='Email of the user.', max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="What is the user's phone number?", max_length=60, null=True)),
                ('first_name', models.CharField(blank=True, help_text="What is the user's first name?", max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, help_text="What is the user's last name?", max_length=60, null=True)),
                ('city', models.CharField(blank=True, help_text="What is the user's city?", max_length=200, null=True)),
                ('currency', models.CharField(choices=[('fiat', 'Fiat'), ('auth', 'Auth')], default='fiat', help_text="What is the user's currency?", max_length=60)),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('driver', 'Driver')], default='buyer', help_text="What is the user's role?", max_length=60)),
                ('card', models.CharField(blank=True, help_text="What is the user's card number?", max_length=60, null=True)),
                ('mm', models.CharField(blank=True, help_text="What is the user's mm?", max_length=60, null=True)),
                ('yy', models.CharField(blank=True, help_text="What is the user's yy?", max_length=60, null=True)),
                ('cvv', models.CharField(blank=True, help_text="What is the user's cvv?", max_length=60, null=True)),
                ('card_holder_name', models.CharField(blank=True, help_text="What is the user's card holder name?", max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Is the user active?')),
                ('is_staff', models.BooleanField(default=False, help_text='Is the user as a staff member?')),
                ('is_superuser', models.BooleanField(default=False, help_text='Is the user a super user?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='ModelAccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('notification', models.BooleanField(default=False, help_text='user notification')),
                ('timezone', timezone_field.fields.TimeZoneField()),
                ('user', models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'Profils',
                'db_table': 'account_profile',
            },
        ),
    ]
