# Generated by Django 3.1.1 on 2020-10-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201008_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccountuser',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code for the user', null=True, upload_to='qr_codes'),
        ),
    ]
