# Generated by Django 3.1.1 on 2020-10-11 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_modelaccountuser_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccountuser',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identification number for the user.', unique=True),
        ),
    ]
