# Generated by Django 3.1.1 on 2020-10-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_modelaccountuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaccountuser',
            name='short_url',
            field=models.CharField(blank=True, help_text='What is the short url for the user.', max_length=100, null=True),
        ),
    ]
