# Generated by Django 3.1.1 on 2020-10-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_modelproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelproduct',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='modelproduct',
            table='product',
        ),
    ]
