# Generated by Django 3.1.1 on 2020-10-28 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201022_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='product_description',
            field=models.CharField(blank=True, help_text='Description of the product.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='product_name',
            field=models.CharField(blank=True, help_text='Name of the product.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='product_price',
            field=models.CharField(blank=True, help_text='Price of the product.', max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='modelproduct',
            name='user',
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='user',
            field=models.ManyToManyField(help_text='The user associated with this product.', related_name='user_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
