# Generated by Django 3.1.1 on 2020-11-21 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201028_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this entry was created in the system')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the table data was last updated in the system')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identification number for the order.', unique=True)),
                ('buyer', models.ManyToManyField(help_text='The buyer associated with this order.', related_name='order_buyer', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The product of the order.', on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='account.modelproduct')),
                ('seller', models.ManyToManyField(help_text='The seller associated with this order.', related_name='order_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
    ]
