# Generated by Django 3.1.1 on 2020-11-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_modelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='product_name',
            field=models.CharField(blank=True, help_text='Name of the order product.', max_length=255, null=True),
        ),
    ]
