# Generated by Django 3.1.1 on 2020-11-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_modelorder_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelorder',
            options={'verbose_name': 'MarketOrder', 'verbose_name_plural': 'MarketOrders'},
        ),
        migrations.AlterModelTable(
            name='modelorder',
            table='market_order',
        ),
    ]
