# Generated by Django 3.1.1 on 2020-11-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201122_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelorder',
            old_name='product_name',
            new_name='product_info_id',
        ),
    ]
