# Generated by Django 3.1.1 on 2020-11-22 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201122_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelorder',
            name='buyer',
        ),
        migrations.AddField(
            model_name='modelorder',
            name='buyer',
            field=models.ForeignKey(help_text='The buyer associated with this order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='product',
            field=models.ForeignKey(help_text='The product of the order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='account.modelproduct'),
        ),
        migrations.RemoveField(
            model_name='modelorder',
            name='seller',
        ),
        migrations.AddField(
            model_name='modelorder',
            name='seller',
            field=models.ForeignKey(help_text='The seller associated with this order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='modelproduct',
            name='user',
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='user',
            field=models.ForeignKey(help_text='The user associated with this product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
