# Generated by Django 3.1.1 on 2020-11-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20201122_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code for the product', null=True, upload_to='qr_codes'),
        ),
    ]
