# Generated by Django 3.1.1 on 2020-11-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_modelorder_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='invoice_path',
            field=models.CharField(blank=True, help_text='URL path of the invoice.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code for the order', null=True, upload_to='qr_codes'),
        ),
    ]
