# Generated by Django 3.1.1 on 2020-11-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20201122_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Number of the invoice.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='modelorder',
            name='xero_Invoice_id',
            field=models.CharField(blank=True, help_text='Xero of the invoice.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='modelorder',
            name='xero_contact_id',
            field=models.CharField(blank=True, help_text='Xero Contact of the invoice.', max_length=250, null=True),
        ),
    ]
