# Generated by Django 3.1.1 on 2020-10-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelMarketPlaceProduct',
        ),
    ]
